### PR TITLE
Full width Epic

### PR DESCRIPTION
**Pull request by webb04**
the width of the epics is a bit too small so there's more space to the right compared to the left. It should take up the whole width

## Screenshots

| Before | After |
| --- | --- |
|  |  |

### CODE REVIEW

**Comment by frankie297** [comment]
Sorry, not sure what has changed here?

**Comment by webb04** [comment]
The screenshot on mobile might be a bit better, the width of the epics is a bit too small so there's more space to the right compared to the left. It should take up the whole width

IMG_6449

**Comment by frankie297** [comment]
@webb04 aha thanks for that! yep gotcha! 👍 💯

**Comment by JamieB-gu** [comment]
> the width of the epics is a bit too small so there's more space to the right compared to the left. It should take up the whole width

Do you want to drop this quote into the main PR description for future reference? 😄

**Review by JamieB-gu — APPROVED** [review]

**Pull request merged**
