### PR TITLE
Live 2636 - Editions Cartoon

### PR DESCRIPTION
**Pull request by abeddow91**
## Why are you doing this?
Cartoons weren't rendering as per design. This PR adds a check to see if the header media is a cartoon and then styles as necessary.

## Screenshots

| Before | After |
| --- | --- |
 |  

 |

### CODE REVIEW

**Comment by JamieB-gu** [comment]
The storyshots file has been deleted? 🤔

**Comment by abeddow91** [comment]
Yeah, I'm not sure why that has happened. I'll take a look into it!

**Comment by abeddow91** [comment]
^^ This is resolved now

**Review by joecowton1 — APPROVED** [review]
LGTM!

**Pull request merged**
