### PR TITLE
LIVE-1880 : Header Media Lightbox

### PR DESCRIPTION
**Pull request by abeddow91**
## Why are you doing this?
~This PR lifts the class name top the parent component of header media so that we can trigger a lightbox on click~

This PR removes the pointer event from the image caption and adds it to summary to unblock the image component.

## Changes

- Disable caption pointer event to unblock image
- Disable dark mode as editions does not currently support dark mode

### CODE REVIEW

**Review by joecowton1 — APPROVED** [review]

**Comment by faresite** [comment]
Hey @abeddow91 just for some context, the image should trigger the image when clicked without moving the classname up? It does work on a regular browser, is it not triggering inside RN's webview?

**Comment by abeddow91** [comment]
@faresite The image classname works fine for images in the body but not for the header image as there is a caption component stacked on top. Testing on my side it doesn't work on browser on in RN without moving the class name up. Perhaps I'm missing something though?

**Comment by faresite** [comment]
@abeddow91 you're right, forgot the caption now takes full width and height. 
May I suggest in this case to use `pointer-events: none;` on the `<figcaption />` and add `pointer-events: auto;` to the button inside (I think it's the `<summary />`). What do you think?
I'm just hesitant for us to break out of the image-rendering's lightbox API if we don't have to.

**Comment by abeddow91** [comment]
@faresite Much more elegant 👍 - I'll update accordingly :)

**Review by joecowton1 — APPROVED** [review]
Nicely done 👍

**Review by faresite — APPROVED** [review]
💡📦

**Pull request merged**
