### PR TITLE
bundlesize check

### PR DESCRIPTION
**Pull request by webb04**
Fail the builds if the client side javascript bundles become too large.

### CODE REVIEW

**Comment by webb04** [comment]
> I suspect you've pushed the `dist/*` files by mistakes? Should that be added to the gitignore?
> 
> If they are added voluntarily, why?

They were added to check the bundle size in GitHub actions, but we should be able to generate the `dist` files in the CI. I'll give that another go

**Comment by JamieB-gu** [comment]
I like this idea, but do we need to rely on a library to do it?

```js
const fs = require('fs');

const sizeLimit = 100000;
const bundle = 'GHGuardianHeadline-Bold.ttf';

if (fs.statSync(bundle).size > sizeLimit) {
    process.exit(1);
} else {
    process.exit(0);
}
```

**Comment by webb04** [comment]
> I like this idea, but do we need to rely on a library to do it?
> 
> ```js
> const fs = require('fs');
> 
> const sizeLimit = 100000;
> const bundle = './dist/assets/article.js';
> 
> if (fs.statSync(bundle).size > sizeLimit) {
>     process.exit(1);
> } else {
>     process.exit(0);
> }
> ```

That's interesting... I think it does some extra things like gzipping, although we could do this ourselves too. The library had a nice reporter feature to GitHub but I was getting 500s when trying to use it.

**Comment by webb04** [comment]
So after doing this it looks like `danger.js` might be better.... https://github.com/facebook/react/pull/14717

**Pull request closed without merging**
