### PR TITLE
Live 2632 offline header videos

### PR DESCRIPTION
**Pull request by joecowton1**
## Why are you doing this?

If a user is offline (and the header video is not already cached), the user will see an error message.

This PR creates a hook to check the online status based on this approach: https://levelup.gitconnected.com/useonlinestatus-a-react-hook-to-know-when-your-app-is-offline-2d06e4e536a

It also creates a placeholder component. It currently uses an inline svg, there is an open PR to add the correct icon to Source after which we should import the SVG from there: https://github.com/guardian/source/pull/840

## Changes

- create `useOnlineStatus` hook
- create `Placeholder` component
- render placeholder in `video` component if offline

## Screenshots

| Before | After |
| --- | --- |
|  |  |

### CODE REVIEW

**Comment by prisalcalde** [comment]
Thanks, @joecowton1 . Looking good to me. Let's ask Ben to take a look as well when he's back!

**Comment by joecowton1** [comment]
> Thanks, @joecowton1 . Looking good to me. Let's ask Ben to take a look as well when he's back!

Ok sure! I'm thinking we maybe we merge it - review permitting - just to check it works properly (its hard to test without it being on a device) but v happy to make any changes :)

**Review by abeddow91 — APPROVED** [review]
Nice work, looks great!

**Review by mohammad-haque — APPROVED** [review]
Nice work! Looks good to me 👍

**Pull request merged**
