### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by webb04**

### CODE REVIEW

**Comment by webb04** [comment]
This seems to be the problem: https://github.com/lodash/lodash/pull/4745

**Comment by JamieB-gu** [comment]
Is this covered by #304?

**Comment by webb04** [comment]
So the vulnerability hasn't been patched yet in Lodash so neither npm audit or Snyk will be able to patch it. I've opened this to unblock open PRs https://github.com/guardian/apps-rendering/pull/309

**Comment by JamieB-gu** [comment]
Snyk offers their own patches for situations where the fix hasn't been implemented in the dependency yet. It looks like that's what #304 has applied.

**Comment by webb04** [comment]
I see, it's not promising that the Snyk check is failing on that PR still

**Comment by JamieB-gu** [comment]
I *think* that's because `snyk protect` isn't being run as part of the GitHub Action, but I'm not 100% on that, looking into it now.

**Pull request closed without merging**
