### PR TITLE
Editions screenshots in CI

### PR DESCRIPTION
**Pull request by faresite**
Make use of the lovely screenshot workflow to add some editions articles. For now I only added:

- Standard
- Opinion
- Review

### CODE REVIEW

**Comment by faresite** [comment]
@jacobwinch @JamieB-gu I'm a bit struggling with this one, I have the feeling the screenshots of `main` are broken because we might need to merge the PR first so they're populated for `main`?!

**Comment by JamieB-gu** [comment]
> I have the feeling the screenshots of `main` are broken because we might need to merge the PR first so they're populated for `main`?!

Yeah that's correct.

I'm a bit puzzled about why the new screenshots just seem to be header images though 🤔

**Comment by faresite** [comment]
> > I have the feeling the screenshots of `main` are broken because we might need to merge the PR first so they're populated for `main`?!
> 
> Yeah that's correct.
> 
> I'm a bit puzzled about why the new screenshots just seem to be header images though 🤔

I believe they're header images at the moment because of the current state of edition-rendering styles.

**Review by JamieB-gu — APPROVED** [review]
> I believe they're header images at the moment because of the current state of edition-rendering styles.

Ah, yeah you're right, they broken 😔 - odd, they were working before... Anyway, unrelated to these changes.

**Pull request merged**
